name: Build
on:
    pull_request: {}
    push:
        branches: [main]
permissions:
  contents: write
# develop pushes and repository_dispatch handled in build_develop.yaml
env:
    # These must be set for fetchdep.sh to get the right branch
    REPOSITORY: ${{ github.repository }}
    PR_NUMBER: ${{ github.event.pull_request.number }}
jobs:
    build:
        name: "Build for GitHub Pages"
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v3
              with:
                  cache: "yarn"

            - name: Install Dependencies
              run: "./scripts/layered.sh"

            - name: Build
              run: "yarn build"
              env:
                VERSION: ${GITHUB_SHA}

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.3
              with:
                BRANCH: gh-pages
                FOLDER: webapp